server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intel_manager
    username: root
    password: goldmine
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Mysql8Dialect
